services:
  painter_service:
    build: ./painter_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./painter_service/:/app/
    ports:
      - 8001:8000

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - painter_service